version: "3"
services:
  db:
    image: mysql:latest
    container_name: fhir-authentication-mysql
    #https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    restart: always
    ports:
      - "3307:3307"
    environment:
    # Using either .env.test or .env variables
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
volumes:
  db:
    driver: local

