version: "3"
services:
  db:
    image: mysql:latest
    container_name: fhir-authentication-mysql
    #https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'fhir-authentication'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
